// <auto-generated />
using System;
using DbContext_PlanTributario;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PlanTributario.Migrations
{
    [DbContext(typeof(Data_))]
    partial class Data_ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("PlanTributario.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataLancamento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImpostoDas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Inss")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProLabore")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProntuarioPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAtendimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lancamentoes", (string)null);
                });

            modelBuilder.Entity("PlanTributario.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoResidencial")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profissao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("PlanTributario.Models.Prontuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntecedentesFamiliares")
                        .HasColumnType("TEXT");

                    b.Property<string>("AntecedentesPessoais")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApresentacaoPaciente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evolucao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamesComplementares")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrequenciaCardiaca")
                        .HasColumnType("TEXT");

                    b.Property<string>("HMA")
                        .HasColumnType("TEXT");

                    b.Property<string>("HMP")
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitosVida")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoriaClinica")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspecaoPalpacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("LancamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NivelDor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlanoTerapeutico")
                        .HasColumnType("TEXT");

                    b.Property<string>("PressaoArterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealizouCirurgia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Saturacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("TratamentosRealizados")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsaMedicamentos")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Prontuario");
                });

            modelBuilder.Entity("PlanTributario.Models.Prontuario", b =>
                {
                    b.HasOne("PlanTributario.Models.Lancamento", "Lancamento")
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanTributario.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lancamento");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
